version: "3"

services:
  verana-front:
    ports:
      - 2904:3000
    build: 
      context: ../
      dockerfile: Dockerfile
    command: yarn start
    environment:
      - NEXT_PUBLIC_PORT=3000
      - NEXT_PUBLIC_BASE_URL=http://localhost:2904
      - NEXT_PUBLIC_VERANA_CHAIN_ID=vna-devnet-1
      - NEXT_PUBLIC_VERANA_CHAIN_NAME=VeranaDevnet1
      - NEXT_PUBLIC_VERANA_RPC_ENDPOINT=http://node1.devnet.verana.network:26657
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT=http://node1.devnet.verana.network:1317
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_DEPOSIT=http://node1.devnet.verana.network:1317/verana/td/v1
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_DID=http://node1.devnet.verana.network:1317/verana/dd/v1
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_TRUST_REGISTRY=http://node1.devnet.verana.network:1317/verana/tr/v1
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_CREDENTIAL_SCHEMA=http://node1.devnet.verana.network:1317/verana/cs/v1
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_INDEXER=http://node1.devnet.verana.network:1317/verana/indexer/v1
      - NEXT_PUBLIC_VERANA_REST_ENDPOINT_METRICS=http://node1.devnet.verana.network:1317/verana/metrics/v1
      - NEXT_PUBLIC_VERANA_SIGN_DIRECT_MODE=true
    networks:
      - verana

networks:
  verana:
    driver: bridge